### ISSUE TITLE
Impressive work! Any chance to integrate this in the future?

### ISSUE THREAD

**Issue by gesen2egee** [LoganBooker/prodigy-plus-schedule-free#3]
https://github.com/iShohei220/adopt
ADOPT: Modified Adam Can Converge with Any β2 with the Optimal Rate

"ADOPT addresses the non-convergence issue of Adam by removing the current gradient from the second moment estimate and changing the order of the momentum update and the normalization by the second moment estimate."

It seems to perform well in convergence with a small batch size. I wonder if these works can be integrated.

**Comment by LoganBooker** [comment]
@gesen2egee Hi, and thanks for your interest!

I did play around with adding ADOPT-like updates to the optimiser, but wasn't successful with a direct implementation. Both Prodigy and Schedule-Free are very sensitive to the way parameter updates are done, and adding another layer of complexity I think makes it hard to reason about what the optimiser is doing.

That said, there may be something in simply applying the second moment updates before the first moment/parameter update, but that would require extensive testing to make sure it works correctly with the other pieces (Prodigy and Schedule-Free).

**Comment by LoganBooker** [comment]
> https://github.com/kyleliang919/C-Optim @LoganBooker Found another interesting one. Could it be integrated?

Implemented as of this commit: https://github.com/LoganBooker/prodigy-plus-schedule-free/commit/2b188d296a8f561714acfdb4b7cbd45148af08d8

Definitely needs more testing, but early results (especially with `use_muon_pp`) have been promising with SDXL LoRA training.

**Comment by LoganBooker** [comment]
Just to expand on this -- ScheduleFree works by replacing the first moment of the optimiser with it's own thing, so this particular feature may have limited effectiveness. I'm trying a few different approaches to see if I can make it work as intended.

**Comment by LoganBooker** [comment]
Regarding C-Optim: After spending more time with this, I don't think there's a way to make it work exactly like the reference implementation, but it should have some effect as-is. We would either need to track the first moment (cancelling out the memory savings the optimiser has), or remove the schedule-free element (which I might consider for a separate optimiser).

As for the original part of this issue -- as of the latest commits I've added an ADOPT-like step, [as mentioned in my first comment](https://github.com/LoganBooker/prodigy-plus-schedule-free/issues/3#issuecomment-2489695197). Essentially, we do everything except clipping the gradient (we already this) and adding the first moment as the update (we kind of already do this already as part of schedule-free). Whether it's better or not coupled with this optimiser, I can't say for sure!

**Comment by JaheimLee** [comment]
Hi, I have a question. Does it make sense to use Adam-atan2 and adopt together?

**Comment by LoganBooker** [comment]
> Hi, I have a question. Does it make sense to use Adam-atan2 and adopt together? @LoganBooker

Hey @JaheimLee, I think if you're just getting started with the optimiser, best to stick with the default settings. If those work without issues, then you can try turning some of the other options on.

Both Adam-atan2 and ADOPT are considering experimental as they both have caveats due to the way Prodigy works. Both have a dampening effect on how quickly the weights are updated, which in turn affects Prodigy's initial LR estimate. Recent commits mostly address this issue with Adam-atan2, but for ADOPT, the second moment is significantly larger than it typically would be at the start of training, and so weight updates are smaller. This won't ruin training or anything, it just means Prodigy may take a much longer time to find the right LR.

They also tackle different aspects of training -- I'd suggest reading the papers linked in the optimiser README to find out more, as they may not have any impact on your particular training configuration (both are aimed a large scale, long training sessions where stability late in training is important).
